# Generated by Django 2.1.5 on 2020-07-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='שם')),
                ('image', models.ImageField(default='default.jpg', upload_to='desktop', verbose_name='image')),
                ('image2', models.ImageField(default='default.jpg', upload_to='mobile', verbose_name='image 2')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
