# Generated by Django 2.1.5 on 2020-06-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\ronio\\OneDrive\\Desktop\\projects\\odm_project\\odm_project\\static_cdn\\media_root'),
        ),
    ]
