# Generated by Django 2.1.5 on 2020-06-29 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200623_0023'),
        ('product', '0002_auto_20200623_0203'),
    ]

    operations = [
    ]
