# Generated by Django 2.1.5 on 2020-07-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200629_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default=models.ImageField(upload_to='C:\\Users\\ronio\\OneDrive\\Desktop\\projects\\odm_project\\odm_project\\static\\media_root/', verbose_name='image'), upload_to='C:\\Users\\ronio\\OneDrive\\Desktop\\projects\\odm_project\\odm_project\\static\\media_root/', verbose_name='image 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\ronio\\OneDrive\\Desktop\\projects\\odm_project\\odm_project\\static\\media_root/', verbose_name='image'),
        ),
    ]
