# Generated by Django 2.1.5 on 2020-07-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200701_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='name'),
        ),
    ]
