# Generated by Django 2.1.5 on 2020-07-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200702_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no image', upload_to='C:\\Users\\ronio\\OneDrive\\Desktop\\projects\\odm_project\\odm_project\\static\\media_root/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='no image', upload_to='C:\\Users\\ronio\\OneDrive\\Desktop\\projects\\odm_project\\odm_project\\static\\media_root/', verbose_name='image 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120, null=True, verbose_name='שם'),
        ),
    ]
